[project]
name = "accelerate-runner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "coverage==7.10.6",
    "pytest==8.4.1",
    "pytest-cov==6.3.0",
    "tdl-client-python==0.33.1",
]
